### ISSUE TITLE
Create PieceSubType Model MVP

### ISSUE THREAD

**Issue by jesmeeker** [jesmeeker/artseen-server#8]

**Comment by brunoramirez12** [comment]
Hello there you can use a class like this
#
class PieceSubType:
    def __init__(self, name, abbreviation):
        self.name = name
        self.abbreviation = abbreviation

    def __repr__(self):
        return f"{self.name} ({self.abbreviation})"

    def to_dict(self):
        return {"name": self.name, "abbreviation": self.abbreviation}

the 'PieceSubType' class has two attributes: name and abbreviation. The '__init__' method initializes these attributes with values passed as arguments.

The '__repr__' method returns a string representation of the 'PieceSubType' instance, which is used when printing or displaying the instance.

The 'to_dict' method returns a dictionary representation of the 'PieceSubType' instance, which can be useful when serializing or deserializing the instance.
